### ISSUE TITLE
Add particle size to the default inventory for pdt=49

### ISSUE THREAD

**Issue by webisu** [NOAA-EMC/wgrib2#258] opened 2024-10-03 15:45 UTC
For pdt=48, the particle size is shown in the default inventory.  For pdt=49,
it isn't shown.  Want the default inventory to unique for different
distinct grib messages.

**Comment by AlysonStahl-NOAA** [comment] 2024-11-20 18:20
Is this a duplicate of #273?

**Comment by webisu** [comment] 2024-11-20 18:43
There was only 1 problem.  So it is a duplicate.

**Closed as completed** 2024-11-20 22:28 UTC
